# Generated by Django 2.2 on 2019-04-29 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timecardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecards',
            name='break_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timecards',
            name='pay',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='timecards',
            name='total_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timecards',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Wages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increase_date', models.DateField()),
                ('wage', models.IntegerField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
