# Generated by Django 2.2.1 on 2019-06-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecardapp', '0002_auto_20190429_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wages',
            name='wage',
            field=models.FloatField(),
        ),
    ]
