# Generated by Django 2.2.1 on 2019-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecardapp', '0003_auto_20190601_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='wages',
            name='last_date',
            field=models.DateField(auto_now=True),
        ),
    ]
