# Generated by Django 2.2.1 on 2019-06-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecardapp', '0004_wages_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wages',
            name='last_date',
            field=models.DateField(),
        ),
    ]
