# Generated by Django 2.2.1 on 2019-06-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timecardapp', '0005_auto_20190602_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wages',
            options={'ordering': ['-increase_date']},
        ),
    ]
