# Generated by Django 2.2.1 on 2019-07-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecardapp', '0008_auto_20190706_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='duration',
        ),
        migrations.AddField(
            model_name='settings',
            name='break_duration',
            field=models.TimeField(null=True),
        ),
    ]
