# Generated by Django 2.2.1 on 2019-07-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecardapp', '0009_auto_20190713_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='break_duration',
            field=models.IntegerField(default=0),
        ),
    ]
