# Generated by Django 2.2.1 on 2019-08-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecardapp', '0010_auto_20190713_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='round_time',
            field=models.IntegerField(default=15),
        ),
    ]
