# Generated by Django 2.2.1 on 2019-08-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecardapp', '0011_settings_round_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='calculate_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='overtime_hours',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='settings',
            name='overtime_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
